{
 "title": "App Overview",
 "tags": [
  "lumen",
  "example",
  "app"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Stack", "label": "stack", "query": "label_values(stack)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(carrot_request_latency_seconds_count, instance)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(carrot_request_latency_seconds_count, method)"
   },
   {
    "name": "route",
    "label": "route",
    "query": "label_values(carrot_request_latency_seconds_count, route)"
   },
   {
    "name": "status_code",
    "label": "status_code",
    "query": "label_values(carrot_request_latency_seconds_count, status_code)"
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SQL metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL query duration",
   "type": "graph",
   "description": "The graph show the 99th and 95th percentile of SQL query duration",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_mysql_query_duration_bucket[1m])) by (le, query))",
     "legendFormat": "95p {{query}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_mysql_query_duration_bucket[1m])) by (le, query))",
     "legendFormat": "99p {{query}}"
    }
   ]
  },
  {
   "title": "MySQL queries count",
   "type": "graph",
   "description": "The graph shows the queries count",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_mysql_query_duration_count[1m]) * 60) by (query) "
    }
   ]
  },
  { "title": "Guzzle metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Guzzle response duration",
   "type": "graph",
   "description": "The graph show the 99th and 95th percentile of guzzle response duration",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_guzzle_response_duration_bucket[1m])) by (le, external_endpoint))",
     "legendFormat": "95p {{external_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_guzzle_response_duration_bucket[1m])) by (le, external_endpoint))",
     "legendFormat": "99p {{external_endpoint}}"
    }
   ]
  },
  {
   "title": "Guzzle response count",
   "type": "graph",
   "description": "The graph shows the guzzle response count",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_guzzle_response_duration_count[1m]) * 60) by (external_endpoint) "
    }
   ]
  },
  { "title": "Incoming Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Incoming response time percentiles",
   "type": "graph",
   "description": "The graph show the 99th and 95th percentile of response time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_response_time_seconds_bucket[1m])) by (le,route)) ",
     "legendFormat": "95p {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_response_time_seconds_bucket[1m])) by (le,route)) ",
     "legendFormat": "99p {{route}}"
    }
   ]
  },
  {
   "title": "Incoming response count",
   "type": "graph",
   "description": "The graph shows the incoming response count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_response_time_seconds_count[1m]) * 60) by (route)"
    }
   ]
  }
 ]
}