version: '3.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${EXAMPLE_APP_NGINX_PORT}:80"
    volumes:
      - .:/app
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  app:
    hostname: app
    container_name: lumen-example-app
    build: ./docker
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - ./conf/apcu-php.ini:/usr/local/etc/php/conf.d/10-docker-php-ext-apcu.ini
    depends_on:
      - prometheus
      - my-sql
  redis:
    hostname: redis
    image: 'redis:3.2'
    command: 'redis-server --requirepass secret'
    ports:
      - '${EXAMPLE_APP_REDIS_PORT}:6379'
  my-sql:
    hostname: my-sql
    image: theasci/docker-mysql-tmpfs
    environment:
      MYSQL_SQL_TO_RUN: >-
        GRANT ALL ON *.* TO "homestead"@"%" IDENTIFIED BY 'secret',
        "homestead"@"127.0.0.1" IDENTIFIED BY 'secret', "homestead"@"localhost"
        IDENTIFIED BY 'secret' WITH GRANT OPTION;
      MYSQLD_RAM_SIZE: 512
      TIMEZONE: UTC
    privileged: true
    ports:
      - '${EXAMPLE_APP_MYSQL_PORT}:3306'
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.4.3
    volumes:
      - './conf/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '${EXAMPLE_APP_PROMETHEUS_PORT}:9090'
  push-gateway:
    hostname: push-gateway
    image: prom/pushgateway
    ports:
      - '${EXAMPLE_APP_PUSH_GATEWAY_PORT}:9091'
  grafana:
    hostname: grafana
    image: grafana/grafana:5.0.4
    ports:
      - '${EXAMPLE_APP_GRAFANA_PORT}:3000'
    depends_on:
      - prometheus
