name: Publish docker images

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: arquivei/laravel-prometheus-exporter
          push: true
          context: .
          file: ./.docker/Dockerfile
          tags: ${{ matrix.php }}
